// REGISTER USER CONSTANT
export const REGISTER_USER_LOADING  = 'REGISTER_USER_LOADING';
export const REGISTER_USER_SUCCESS  = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR  = 'REGISTER_USER_ERROR';
export const REMOVE_REGISTER_USER_ERROR  = 'REMOVE_REGISTER_USER_ERROR';