// REGISTER USER CONSTANT
export const REGISTER_USER_LOADING  = 'REGISTER_USER_LOADING';
export const REGISTER_USER_SUCCESS  = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR  = 'REGISTER_USER_ERROR';
export const REMOVE_REGISTER_USER_ERROR  = 'REMOVE_REGISTER_USER_ERROR';

//LOGIN USER CONSTANT
export const LOGIN_USER_LOADING  = 'LOGIN_USER_LOADING';
export const LOGIN_USER_SUCCESS  = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR  = 'LOGIN_USER_ERROR';
export const REMOVE_LOGIN_USER_ERROR  = 'REMOVE_LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';


//PROFILE CONSTANT
export const UPDATE_PROFILE_LOADING = 'UPDATE_PROFILE_LOADING';
export const UPDATE_PROFILE_COMPLETED = 'UPDATE_PROFILE_COMPLETED';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const GET_PROFILE_LOADING = 'GET_PROFILE_LOADING';
export const GET_PROFILE_COMPLETED = 'GET_PROFILE_COMPLETED';
export const GET_PROFILE_UNCOMPLETED = 'GET_PROFILE_UNCOMPLETED';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
export const REMOVE_PROFILE_ERROR = "REMOVE_PROFILE_ERROR";



